name: Create Release

on:
  create:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Zip Folder
        run: zip -r judoijatracker.zip index.html assets LICENSE
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "judoijatracker.zip"